function plot_LL_figure4(spikes,result,params,Distances,threshold)
% PLOT_LL_FIGURE4 Generates composite summary plot reproducing Figure 4.
%
%   Renders a multi-panel figure displaying spike raster plots, pairwise distance 
%   matrices, discrimination matrices, single-neuron performance, population 
%   performance, and optimal neuron selection.
%
%   Valid call structure:
%
%   .. code-block:: matlab
%
%      plot_LL_figure4(spikes, result, params, Distances, threshold);
%
%   :param spikes: 3D cell array of size `[N x S x R]` containing spike times.
%   :type spikes: cell
%   :param result: Result structure generated by :func:`evaluate_LL_population`.
%   :type result: struct
%   :param params: Simulation parameter structure containing at least `Tmax`.
%   :type params: struct
%   :param Distances: Distance metric configuration parameter.
%   :type Distances: string or cell
%   :param threshold: Distance calculation threshold.
%   :type threshold: double
%
%   .. note::
%
%      **Panel Layout Structure:**
%
%      * **Panel B:** Spike raster plots per neuron and stimulus.
%      * **Panel C:** Single-neuron pairwise distance matrices (:math:`D_n`).
%      * **Panel D:** Single-neuron discrimination matrices (:math:`M_n`).
%      * **Panel E:** Single-neuron performance matrices (:math:`P_n`).
%      * **Panel F:** Global population performance matrix (:math:`P`).
%      * **Panel G:** Best-performing neuron map (:math:`M`).
    
    [N,S,R] = size(spikes);
    
    fs = 10;
    linewid = 1.5;
    
    figure('Color','w','Renderer','painters','Units','normalized','Position',[0.05 0.05 0.90 0.88]);
    
    %% ==============================
    %% COLORS
    %% ==============================
    
    ColormapLL = [...
        0 0 0
        0 0 1
        1 0 0
        0 0.5 0
        1 1 0];
    
    %% ==============================
    %% LAYOUT
    %% ==============================
    
    leftMargin   = 0.05;
    bottomMargin = 0.08;
    
    panelBWidth  = 0.47;
    panelBHeight = 0.72;
    
    columnWidth  = 0.085;
    columnGap    = 0.018;
    
    xC = leftMargin + panelBWidth + 0.03;
    xD = xC + columnWidth + columnGap;
    xE = xD + columnWidth + columnGap;
    
    gapX = 0.01;
    gapY = 0.01;
    
    cellWidth  = (panelBWidth - (S-1)*gapX) / S;
    cellHeight = (panelBHeight - (N-1)*gapY)/ N;
    
    %% ==============================
    %% PANEL B
    %% ==============================
    
    for n = 1:N
    
        for s = 1:S
    
            xpos = leftMargin + (s-1)*(cellWidth+gapX);
            ypos = bottomMargin + (N-n)*(cellHeight+gapY);
    
            ax = axes('Position',[xpos ypos cellWidth cellHeight]);
    
            hold(ax,'on')
    
            for r = 1:R
    
                st = spikes{n,s,r};
    
                if isempty(st)
                    continue
                end
    
                plot(ax,...
                     st,...
                     r*ones(size(st)),...
                     'k|',...
                     'MarkerSize',6);
    
            end
    
            xlim(ax,[0 params.Tmax])
            ylim(ax,[0 R+1])
    
            set(ax,...
                'XTick',[],...
                'YTick',[]);
    
            box(ax,'on')
    
            if n==1
                title(ax,...
                    sprintf('Stimulus %d',s),...
                    'FontWeight','bold',...
                    'FontSize',fs);
            end
    
            if s==1
                ylabel(ax,...
                    sprintf('Neuron %d',n),...
                    'FontWeight','bold',...
                    'FontSize',fs);
            end
    
            if n==N
                xlabel(ax,'Time');
            end
    
        end
    
    end
    
    annotation('textbox',...
        [leftMargin-0.03 bottomMargin+panelBHeight+0.01 0.02 0.02],...
        'String','B',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% =================================================
    %% SCALE OF DISTANCE / PERFORMANCE MATRICES
    %% =================================================
    
    maxD = 0;
    maxP = 0;
    
    for n = 1:N
        maxD = max(maxD,max(result.DistanceMatrix{n}(:)));
        maxP = max(maxP,max(result.Mn{n}(:)));
    end
    
    %% ====================================
    %% POSITIONS OF C D E COLUMNS
    %% ====================================
    
    rowHeight = panelBHeight/N;
    
    %% ==============================
    %% PANEL C
    %% ==============================
    
    for n = 1:N
    
        ypos = bottomMargin + (N-n)*rowHeight;
    
        ax = axes('Position',[xC ypos columnWidth rowHeight]);
    
        imagesc(result.DistanceMatrix{n});
    
        axis(ax,'image');
        axis(ax,'off');
    
        colormap(ax,jet);
        caxis(ax,[0 maxD]);
    
        title(ax,sprintf('D_{%d}',n),...
            'FontWeight','bold',...
            'FontSize',fs);
    
    end
    
    annotation('textbox',...
        [xC-0.03 bottomMargin+panelBHeight+0.01 0.02 0.02],...
        'String','C',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% ==============================
    %% PANEL D
    %% ==============================
    
    for n = 1:N
    
        ypos = bottomMargin + (N-n)*rowHeight;
    
        ax = axes('Position',[xD ypos columnWidth rowHeight]);
    
        imagesc(result.Discrimination{n}*n);
    
        axis(ax,'image');
        axis(ax,'off');
    
        colormap(ax,ColormapLL);
        caxis(ax,[0 4]);
    
        title(ax,sprintf('M_{%d}',n),...
            'FontWeight','bold',...
            'FontSize',fs);
    
        hold(ax,'on');
        DrawSeparators(S,1,linewid);
        hold(ax,'off');
    
    end
    
    annotation('textbox',...
        [xD-0.03 bottomMargin+panelBHeight+0.01 0.02 0.02],...
        'String','D',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% ==============================
    %% PANEL E
    %% ==============================
    
    for n = 1:N
    
        ypos = bottomMargin + (N-n)*rowHeight;
    
        ax = axes('Position',[xE ypos columnWidth rowHeight]);
    
        imagesc(result.Mn{n});
    
        axis(ax,'image');
        axis(ax,'off');
    
        colormap(ax,jet);
        caxis(ax,[0 maxP]);
    
        title(ax,sprintf('P_{%d}',n),...
            'FontWeight','bold',...
            'FontSize',fs);
    
        hold(ax,'on');
        DrawSeparators(S,1,linewid);
        hold(ax,'off');
    
    end
    
    annotation('textbox',...
        [xE-0.03 bottomMargin+panelBHeight+0.01 0.02 0.02],...
        'String','E',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% ==================================
    %% POSITION OF F AND G
    %% ==================================
    
    FGy = bottomMargin + panelBHeight + 0.04;
    
    xF = xE;
    xG = xD;
    
    %% ==============================
    %% PANEL F
    %% ==============================
    
    axF = axes('Position',[xF FGy columnWidth columnWidth]);
    
    imagesc(result.populationPerformance);
    
    axis(axF,'image');
    axis(axF,'off');
    
    colormap(axF,jet);
    caxis(axF,[0 maxP]);
    
    title(axF,'P',...
        'FontWeight','bold',...
        'FontSize',fs);
    
    hold(axF,'on');
    DrawSeparators(S,1,linewid);
    hold(axF,'off');
    
    annotation('textbox',...
        [xF-0.03 FGy+columnWidth+0.005 0.02 0.02],...
        'String','F',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% ==============================
    %% PANEL G
    %% ==============================
    
    axG = axes('Position',[xG FGy columnWidth columnWidth]);
    
    imagesc(result.bestNeuronMatrix);
    
    axis(axG,'image');
    axis(axG,'off');
    
    colormap(axG,ColormapLL);
    caxis(axG,[0 4]);
    
    title(axG,'M',...
        'FontWeight','bold',...
        'FontSize',fs);
    
    hold(axG,'on');
    
    DrawSeparators(S,1,linewid);
    
    txt = sprintf('%d ',result.bestPopulation);
    
    text(axG,...
        S/1.5,...
        S+0.9,...
        txt,...
        'HorizontalAlignment','center',...
        'FontWeight','bold',...
        'FontSize',fs);
    
    hold(axG,'off');
    
    annotation('textbox',...
        [xG-0.03 FGy+columnWidth+0.005 0.02 0.02],...
        'String','G',...
        'LineStyle','none',...
        'FontWeight','bold',...
        'FontSize',12);
    
    %% ==============================
    %% ARROWS
    %% ==============================
    
    % B -> C
    annotation('arrow',...
        [leftMargin+panelBWidth+0.005 xC-0.005],...
        [bottomMargin+panelBHeight/2 bottomMargin+panelBHeight/2],...
        'LineWidth',2);
    
    % C -> D
    annotation('arrow',...
        [xC+columnWidth+0.005 xD-0.005],...
        [bottomMargin+panelBHeight/2 bottomMargin+panelBHeight/2],...
        'LineWidth',2);
    
    % D -> E
    annotation('arrow',...
        [xD+columnWidth+0.005 xE-0.005],...
        [bottomMargin+panelBHeight/2 bottomMargin+panelBHeight/2],...
        'LineWidth',2);
    
    % E -> F
    annotation('arrow',...
        [xF+columnWidth/2 xF+columnWidth/2],...
        [bottomMargin+panelBHeight+0.005 FGy-0.005],...
        'LineWidth',2);
    
    % G -> F
    annotation('arrow',...
        [xF-0.005 xG+columnWidth],...
        [FGy+columnWidth/2 FGy+columnWidth/2],...
        'LineWidth',2);
    
    %% ==========================================================
    %% RECTANGLES AROUND SELECTED PERFORMANCE MATRICES
    %% ==========================================================
    
    bestPop = result.bestPopulation(:)';
    
    for n = bestPop
    
        ypos = bottomMargin + (N-n)*rowHeight + 1.8*gapY;
    
        annotation('rectangle',...
            [xE-gapX/5 ypos columnWidth+gapX/2.5 rowHeight-1.4*gapY],...
            'LineWidth',2,...
            'Color','k');
    
    end
    
    %% ==============================
    %% SUMMARY
    %% ==============================
    
    fprintf('\n===== LL RESULTS =====\n');
    fprintf('Best population: ');
    fprintf('%d ',result.bestPopulation);
    fprintf('\n');
    fprintf('PLL = %.4f\n',result.bestP);
    fprintf('======================\n');

end